name: HungerCraftGames
version: '${project.version}'
main: me.thejokerdev.hungercraftgames.Main
api-version: 1.17
authors: [ TheJokerDev ]
description: HungerGames for Tournament

softdepend:
  - voicechat
  - ProtocolLib
  - PlaceholderAPI

commands:
  hungergames:
    aliases:
      - hg
      - hcg
    usage: /hungergames